ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'COMPANY_MANAGE_OPERATIONS';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'COMPANY_VIEW_FINANCIAL_SUMMARIES';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'COMPANY_VIEW_ANALYTICS';
