import express from "express";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import farmRoutes from "./farmRoutes";
import batchRoutes from "./batchRoutes";
import dealerRoutes from "./dealerRoutes";
import dealerProductRoutes from "./dealerProductRoutes";
import dealerSaleRoutes from "./dealerSaleRoutes";
import consignmentRoutes from "./consignmentRoutes";
import dealerLedgerRoutes from "./dealerLedgerRoutes";
import companyProductRoutes from "./companyProductRoutes";
import companySaleRoutes from "./companySaleRoutes";
import companyLedgerRoutes from "./companyLedgerRoutes";
import paymentRequestRoutes from "./paymentRequestRoutes";
import medicalSupplierRoutes from "./medicalSupplierRoutes";
import hatcheryRoutes from "./hatcheryRoutes";
import inventoryRoutes from "./inventoryRoutes";
import expenseRoutes from "./expenseRoutes";
import salesRoutes from "./salesRoutes";
import reminderRoutes from "./reminderRoutes";
import reminderNotificationRoutes from "./reminderNotificationRoutes";
import notificationActionRoutes from "./notificationActionRoutes";
import vaccinationRoutes from "./vaccinationRoutes";
import dashboardRoutes from "./dashboardRoutes";
import conversationRoutes from "./conversationRoutes";
import messageRoutes from "./messageRoutes";
import doctorRoutes from "./doctorRoutes";
import mortalityRoutes from "./mortalityRoutes";
import batchShareRoutes from "./batchShareRoutes";
import weightRoutes from "./weightRoutes";
import s3Routes from "./s3Routes";
import notificationRoutes from "./notificationRoutes";
import mortalityNotificationRoutes from "./mortalityNotificationRoutes";
import feedNotificationRoutes from "./feedNotificationRoutes";
import expenseNotificationRoutes from "./expenseNotificationRoutes";
import inventoryNotificationRoutes from "./inventoryNotificationRoutes";
import accountRoutes from "./accountRoutes";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/farms", farmRoutes);
router.use("/batches", batchRoutes);
router.use("/dealers", dealerRoutes);
router.use("/dealer/products", dealerProductRoutes);
router.use("/dealer/sales", dealerSaleRoutes);
router.use("/consignments", consignmentRoutes);
router.use("/dealer/ledger", dealerLedgerRoutes);
router.use("/company/products", companyProductRoutes);
router.use("/company/sales", companySaleRoutes);
router.use("/company/ledger", companyLedgerRoutes);
router.use("/payment-requests", paymentRequestRoutes);
router.use("/medical-suppliers", medicalSupplierRoutes);
router.use("/hatcheries", hatcheryRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/expenses", expenseRoutes);
router.use("/sales", salesRoutes);
router.use("/reminders", reminderRoutes);
router.use("/reminder-notifications", reminderNotificationRoutes);
router.use("/notification-actions", notificationActionRoutes);
router.use("/vaccinations", vaccinationRoutes);  
router.use("/dashboard", dashboardRoutes);
router.use("/conversations", conversationRoutes);
router.use("/messages", messageRoutes);
router.use("/doctors", doctorRoutes);
router.use("/mortalities", mortalityRoutes);
router.use("/batch-share", batchShareRoutes);
router.use("/batches", weightRoutes); // Weight routes for batches
router.use("/s3", s3Routes);
router.use("/notifications", notificationRoutes);
router.use("/mortality-notifications", mortalityNotificationRoutes);
router.use("/feed-notifications", feedNotificationRoutes);
router.use("/expense-notifications", expenseNotificationRoutes);
router.use("/inventory-notifications", inventoryNotificationRoutes);
router.use("/account", accountRoutes);

export default router;
