ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'FARMER_MANAGE_OPERATIONS';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'FARMER_VIEW_FINANCIAL_SUMMARIES';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'FARMER_VIEW_CASH_HISTORY';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'FARMER_VIEW_ANALYTICS';
ALTER TYPE "StaffPermission" ADD VALUE IF NOT EXISTS 'FARMER_VIEW_STAFF_MANAGEMENT';
